### ISSUE TITLE
Второй параметр функции getLastResponsibleNumber всегда 120

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleSmartIVR#5]
В параметре функции [getLastResponsibleNumber](https://github.com/mikopbx/ModuleSmartIVR/blob/d6f5a7bca30c965b24f121aa661ca8a9fc2fca64/Lib/AGICallLogic.php#L102 всегда 120, а то что в интерфейсе указываешь никак не используется в модуле

**Comment by jorikfon** [comment]
И еще бы дописать в интерфейсе, что при установке в 0, механизм переадресации будет отключен. Может быть потом красоту навести сделать бегунок, если его дергаешь, ставит параметр в 0 и прячет его, если взводишь, появляются поля для настройки этой функции. 

А может вообще как отдельный модуль это сделать, платный, и использовать новый механизм interception со звонком во время маршрутизации...
